# NOTE: https://github.com/driesvints/dotfiles/blob/main/.macos

- name: mac settings are changed
  command: 'defaults write {{ item }}'
  with_items:
    - 'NSGlobalDomain ApplePressAndHoldEnabled 0'
    - 'com.apple.systempreferences TMShowUnsupportedNetworkVolumes 1'
    - 'com.apple.desktopservices DSDontWriteNetworkStores true'
    - 'com.apple.TextEdit RichText 0'
    - 'com.apple.dock autohide -bool true'
    - 'com.apple.finder AppleShowAllFiles true'
    - 'com.apple.finder QuitMenuItem -bool true'
    # Use list view in all Finder windows by default
    - 'com.apple.finder FXPreferredViewStyle -string "Nlsv"'
    # Bottom right screen corner → Start screen saver
    - 'com.apple.dock wvous-br-corner -int 5'
    - 'com.apple.dock wvous-br-modifier -int 0'
    # Set Dock behaviour
    - 'com.apple.dock orientation -string left'
    - 'com.apple.dock autohide-delay -float 0'
    # Safari
    - 'com.apple.Safari AutoOpenSafeDownloads -bool false'
    - 'com.apple.Safari IncludeInternalDebugMenu -bool true'
    # Enable the Develop menu and the Web Inspector in Safari
    - 'com.apple.Safari IncludeDevelopMenu -bool true'
    - 'com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true'
    - 'com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true'
    # Get Dark Menu bar, Dock and Spotlight for macOS Mojave
    - '-g NSRequiresAquaSystemAppearance -bool Yes'
    - 'com.apple.Spotlight NSRequiresAquaSystemAppearance -bool No'
    # Menubar
    - 'com.apple.menuextra.battery ShowPercent -string "YES"'
  changed_when: false
